### ISSUE TITLE
transparent window immediately closes

### ISSUE THREAD

**Issue by Double-Lv** [meslzy/electron-as-wallpaper#11]
Hello,

When I specify transparent: true, the browserWindow opens briefly and then immediately closes. And when I set transparent: false, the window didn't closes. It seems there might be an issue with the support for the transparent property. My environment details are as follows:

Operating System: Windows 10
Electron Version: 25.9.8

My code:

```ts
const widgetWindow = new WidgetBrowserWindow({
    width: 600,
    height: 300,
    x: 100,
    y: 100,
    hasShadow: false,
    frame: false,
    transparent: true,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    enableLargerThanScreen: true,
    resizable: false,
    webPreferences: {
        webSecurity: false,
        contextIsolation: false,
        nodeIntegration: true,
        enableRemoteModule: true,
        allowRunningInsecureContent: true,
    }
  });
const winURL = process.env.NODE_ENV === 'development'
    ? 'http://localhost:6879/widget.html'
    : `file://${__dirname}/widget.html`;

require('@electron/remote/main').enable(widgetWindow.webContents);

widgetWindow.once('ready-to-show', () => {
    if (__DEBUG__ && !config.showDevTools) {
      widgetWindow.webContents.closeDevTools();
    }

  attach(widgetWindow, {
    forwardKeyboardInput: true,
    forwardMouseInput: true,
    transparent: true
  });

  widgetWindow.show();
});

widgetWindow.loadURL(winURL);
```

By the way, I use electron-as-wallpaper with the commit: 86e3f94b8f16b7edae101e40402bb97c867f3edd  （before your Refactor）, because my Application can only run with node16

Thank you.

**Comment by Double-Lv** [comment]
> Hey, Thanks for reporting the issue, But.
> 
> * First, There's no issue of using any node version as far as my knowledge goes.
> * I can't really go back to prev commit and test the code, so i test using the latest commit and it works well as showing below.
> 
> ![image](https://private-user-images.githubusercontent.com/44545101/307401711-4af5fd99-9861-4f3d-b5b3-c5259c83b466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDMwOTgsIm5iZiI6MTcwODg0Mjc5OCwicGF0aCI6Ii80NDU0NTEwMS8zMDc0MDE3MTEtNGFmNWZkOTktOTg2MS00ZjNkLWI1YjMtYzUyNTljODNiNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA2MzMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzE2ZjAzYTkzYzFkMDE5NDVlZGRjYzA5ZjY5Mjc2YmQyZDM1NzM4YjY2YThmNWJhMDcyNTZkNzNkYjJiYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3zcdqsLMMOeFvLwOB70GLrQxpUaBI9qUHYMNy-SY6Ls)
> 
> * Can you try using the latest version ?
> * Can you please create a repo for it and send it over with more details of what's goin on, try to use logs, etc.
> 
> I can't solve issue unless i see errors or bugs.

Hello，I'm unable to obtain logs because the window immediately crashes，and devTools didn't show any error. I've updated electron-as-wallpaper to the latest code, but the issue persists. Could you please try running nodejs16 locally to see if it works for you?

**Comment by meslzy** [comment]
Yes, i used nodes 16 on windows 10.

**Comment by Double-Lv** [comment]
Thank you very much for the response. I've finally identified the root cause of my problem. It turns out that in my code:
`app.disableHardwareAcceleration();`
This line is causing the crash. I added this line because GPU rendering was slowing down my app (although I'm not sure why).

**Comment by meslzy** [comment]
I see, thanks for reporting this, I'll try to add note abt it, also I'll try to figure out the issue.

I'll close this issue unless you have something to add.
