### ISSUE TITLE
 support drag and resize

### ISSUE THREAD

**Issue by Double-Lv** [meslzy/electron-as-wallpaper#12]
Hello meslzy: 
Currently, it works well for me, but it does not support drag and resize of window. Can you continue working to support this?

**Comment by meslzy** [comment]
This is really out of the scope of this library, adding such a feature like this is unnecessary if my main goal is creating frameless window.


You can listen to the mouse event and check when the user hover and hold on the window header and when it moves try to calculate and move the window to.

**Comment by Double-Lv** [comment]
Thank you for your reminder. I've come up with a solution: calling detach once before the user resizes and then calling attach again after the resizing is completed.
However, I've encountered a new issue. When I call attach again, it throws an error:
```
TypeError: Could not register raw input window class
    at attach (C:\work\flicker\node_modules\electron-as-wallpaper\dist\main.js:20:23)
```

**Comment by meslzy** [comment]
Sorry for my mistake, I didn't cleanup in good way, I have fixed the issue.

- please use version `1.0.7`

```bash
npm i electron-as-wallpaper@1.0.7
```

**Comment by Double-Lv** [comment]
It worked! I'm really grateful to you.
