### ISSUE TITLE
cannot support Chinese input method

### ISSUE THREAD

**Issue by Double-Lv** [meslzy/electron-as-wallpaper#13]
![image](https://github.com/meslzy/electron-as-wallpaper/assets/4505130/a2b937b3-1ac8-40d0-94d1-5e7aa0415534)
Hello meslzy:
When I input Chinese characters in the red box here, the input method software appears below the screen. However, when I finish inputting and press the spacebar, it doesn't input Chinese characters but instead inputs letters.
When I execute 'detach', It works fine.

**Comment by meslzy** [comment]
I didn't understand at all. 

What i did understand is that we have an input and when we click on it a software popup which i don't have clue what is it.

Then when you type word and you click space it transfer back the words to the app input.

Can you please lemme know the software name that u use to type Chinese.

**Comment by Double-Lv** [comment]
The input software is [https://shurufa.sogou.com/](https://shurufa.sogou.com/)
What I expect is like this
<img width="841" alt="image" src="https://github.com/meslzy/electron-as-wallpaper/assets/4505130/3f1f9190-a175-4fc9-abee-53677b2a0cbb">
When I type space, It should input "中文"，but now It's "zhongw"

**Comment by meslzy** [comment]
Well, I'm not Chinese, i really need your help, i have no idea how to use the software.
Can we use faster channel to comms, maybe Discord?

**Comment by meslzy** [comment]
Okay i see now, i had to change my language first. 

![image](https://github.com/meslzy/electron-as-wallpaper/assets/44545101/af65243a-5890-46f5-817d-43632bb54335)

The issue here is simple, when you start typing and finish the word the software will send the word to the input in which window is focused. but the issue here is the windows behind desktop can't be focused, so ill try to see if we can solve this issue or not.

**Comment by meslzy** [comment]
Hey, after a lot of debugging and searching i think this is beyond my experience, sorry but i can't solve this issue.

**Comment by Double-Lv** [comment]
Ok, Thank you so much!

**Comment by Double-Lv** [comment]
Hi @meslzy 
I'm trying out a solution and would like to ask: Is it possible for me to make the window a child window of the desktop rather than a wallpaper, so that I can input Chinese? I want the window to be a child window of the desktop because I don't want it to disappear when the user clicks 'Show Desktop'(win+D).

Here's my idea, but I'm unsure how to implement it because I lack knowledge in Windows app development. I tried the following code in main.cpp, but it didn't work:
`
LONG_PTR style = GetWindowLongPtr(windowHandle, GWL_STYLE);

style |= WS_CHILD;

SetWindowLongPtr(windowHandle, GWL_STYLE, style);

SetWindowPos(windowHandle, NULL, 0, 0, 0, 0, SWP_FRAMECHANGED | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);

SetParent(windowHandle, GetDesktopWindow());
`
Is there anything wrong?

**Comment by meslzy** [comment]
I believe i have tried your idea if I'm not mistaken i successfully did it.

What you need is to place it at the bottom of all handlers. (desktop)

Then you need to listen when user change the window state either by (win + d, or click the preview desktop) and prevent that and keep it visible.

I think it's a good idea I'll try to implement it and I'll name it stick and unstick 😎

**Comment by Double-Lv** [comment]
That will be more powerful. I'm looking forward to it :)
