### ISSUE TITLE
LInux and MacOS support?

### ISSUE THREAD

**Issue by dengbuqi** [meslzy/electron-as-wallpaper#16]
Is it possible to provide the Linux and MacOS support?
That will be very awesome!
Thank you!

**Comment by Jarvay** [comment]
You may set option `type` to `desktop` when you create a `BrowserWindow`

**Comment by meslzy** [comment]
I'm Sorry but i have no plane to support `Linux` and `MacOS` now, maybe if you link useful resource ill try.

**Comment by ruofee** [comment]
> Is it possible to provide the Linux and MacOS support? That will be very awesome! Thank you!

Agree it!!

**Comment by ruofee** [comment]
> Is it possible to provide the Linux and MacOS support? That will be very awesome! Thank you!

I found that electron support it on macos! U can set type as "desktop".

**Comment by dengbuqi** [comment]
> > Is it possible to provide the Linux and MacOS support? That will be very awesome! Thank you!
> 
> I found that electron support it on macos! U can set type as "desktop".

Thank you!
