### ISSUE TITLE
多显示器创建多个窗口情况 窗口投放只会出现一个

### ISSUE THREAD

**Issue by 424490034** [meslzy/electron-as-wallpaper#18]
能否通过外部传入显示屏下标 将不同窗口分开设置

**Comment by 424490034** [comment]
> 能否通过外部传入显示屏下标 将不同窗口分开设置 ![image](https://github.com/meslzy/electron-as-wallpaper/assets/49580703/ac99f5cf-95e0-4007-b679-cd80692516d9)

**Comment by meslzy** [comment]
Hey, can you please explain the issue in Stander English plz.

**Comment by 424490034** [comment]
I want to put the elecctron window inside my desktop wallpaper and use it as a video wallpaper. But now I run into a problem where I have multiple monitors and there is a window that I want to have in the desktop wallpaper of each of my monitors.
So I was wondering if it would be possible to provide an additional parameter for each display separately, which would allow me to configure it separately.

**Comment by meslzy** [comment]
Electron provide us with [screen](https://www.electronjs.org/docs/latest/api/screen) object, which has screen details like screen size, bounds, etc.

look at the demo [here](https://github.com/meslzy/electron-as-wallpaper/blob/main/examples/screen-size-changed/index.js)

Microsoft Windows use x, y to position screen which can be used to place ur window at in any screen using the screen bounds 

https://learn.microsoft.com/en-us/windows/win32/gdi/window-coordinate-system

```ts
import {screen} from "electron";

// screen.getAllDisplays will return list of monitors
const [display1, display2] = screen.getAllDisplays();

// https://www.electronjs.org/docs/latest/api/structures/rectangle
// x number - The x coordinate of the origin of the rectangle (must be an integer).
// y number - The y coordinate of the origin of the rectangle (must be an integer).
// width number - The width of the rectangle (must be an integer).
// height number - The height of the rectangle (must be an integer).
display1.bound // { x, y, width, height }
display2.bound // { x, y, width, height }
```

now u can use thus values to place ur windows at any position.

**Comment by 424490034** [comment]
Yes, I coded it that way, but after attach() is used,windows overlaps together instead of in the desktop wallpaper of the corresponding monitor
![image](https://github.com/meslzy/electron-as-wallpaper/assets/49580703/624ecd01-3d13-4b74-9233-c7f21655d3c7)

**Comment by meslzy** [comment]
Can you share your code plz, i don't understand the screenshot you attached.

**Comment by 424490034** [comment]
Okay, this is the code repository https://github.com/424490034/electron-wallpaper

**Comment by meslzy** [comment]
Seems the issue happen when fullscreen is enabled.

if i do this
```ts
wallWindow = new BrowserWindow({
  opacity: 0,
  frame: false,
  fullscreen: false, // i disabled fullscreen
  ...rest ur config
});
```

i get the result we both want
![image](https://github.com/meslzy/electron-as-wallpaper/assets/44545101/2c869a15-f4b2-46d3-bb55-e9117daa26d8)

but when i enable the Fullscreen i got this
![image](https://github.com/meslzy/electron-as-wallpaper/assets/44545101/ea11a6ac-30e2-48f5-a1e0-bab8d700ea18)

**when you create the window u said start full screen which means maximize and what was the screen the window on when it first created? it was on screen 1, so changing the position wont take any effect (bound), you have two solution**

1. use bounds before u create the window

```ts
wallWindow = new BrowserWindow({
  opacity: 0,
  // transparent: true,
  frame: false,
  fullscreen: true,
  x: display.bounds.x, // x
  y: display.bounds.y, // y
  width: display.bounds.width, // width
  height: display.bounds.height, // height
  webPreferences: {
    webSecurity: false,
    devTools: process.env.NODE_ENV === 'development',
    nodeIntegration: true,
    nodeIntegrationInWorker: true,
    // nodeIntegrationInSubFrames: true,
    contextIsolation: true,
  },
});
```

2. just dont use fullscreen not sure if its useful anyway

**Comment by 424490034** [comment]
Ok, thank you very much for your answer
