### ISSUE TITLE
`Attach()` places the windows incorrectly on Windows 10

### ISSUE THREAD

**Issue by tisbutanalt2** [meslzy/electron-as-wallpaper#19]
Love the idea of this library, as I am working on a (not so innocent) app!
Only issue is that when I attach the windows to the desktop, they are very much incorrectly positioned on my screen.

I have three monitors that I tested this on. One is a vertical, and the other two horizontal.
All monitors are 1920x1080 monitors.

I ensured that each window is positioned correctly without using `attach()`
I followed the example for multi-monitor handling, but the windows were very awkwardly positioned.

**Comment by meslzy** [comment]
Hey, Sorry for the late response, can you show me screenshot and code plz.
