### ISSUE TITLE
Not works on win11 24h2

### ISSUE THREAD

**Issue by Jarvay** [meslzy/electron-as-wallpaper#22]
![image](https://github.com/user-attachments/assets/29fc47cd-8308-4e03-8d12-8636ee1866b7)
It shows this error after updating to 24h2.
And i found that `rosepack` has been removed so i could not install this dependency by running `yarn`.

**Comment by meslzy** [comment]
Okay I'll fix it and release it soon. Sorry for the delay.

**Comment by meslzy** [comment]
#23 will solve this issue, please be patient.
