### ISSUE TITLE
MacOS support planned/possible?

### ISSUE THREAD

**Issue by rendomnet** [meslzy/electron-as-wallpaper#25]
Hello. I appreciate that you have developed this module. Will there be support for MacOS?

**Comment by meslzy** [comment]
Hey, thank you for using it, electron already added this feature for MacOS.

![image](https://github.com/user-attachments/assets/67db5d6f-67de-4583-96fc-e82eab4f40e2)

the only issue with their approach is you can't receive input or mouse movement

**Comment by meslzy** [comment]
closing the issue, no response.
