### ISSUE TITLE
enable mouse with electron-as-wallpaper

### ISSUE THREAD

**Issue by Devoron** [meslzy/electron-as-wallpaper#4]
hello! Thanks a lot! I use the library to make the application, but HTML does not receive mouse events. In what direction should I look for?

**Comment by meslzy** [comment]
Hey, ya mouse and keyboard input won't work but u can listen to keyboard and mouse movements by using nodejs naive library called "IoHook"

Or u can forwarding the keyboard input the windows using c++, see [here](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput)


This my answer for now, but I'm planning to add this feature to the library so I'm making this a feature request.

**Comment by lanistor** [comment]
@meslzy Any news on this?

**Comment by meslzy** [comment]
> @meslzy Any news on this?

ya im working on it, i think i can get it soon 🌹.

**Comment by lanistor** [comment]
> > @meslzy Any news on this?
> 
> ya im working on it, i think i can get it soon 🌹.

Really looking forward to it.

**Comment by meslzy** [comment]
I have completed the work, but I am aware that there may still be issues present since I have not tested all scenarios such as multi-desktop and native position. I will continue to work on testing and improving the code to ensure its reliability.

**Comment by lanistor** [comment]
@meslzy Have you tested in window11? 
I tested, it can't work in windows11, my environment is: `node 16.20.1`, node arch is `ia32`, and i have rebuild by `nody-gyp rebuild` to create matched binary files of `electron-as-wallpaper`(i cloned this project instead of install it).

**Comment by lanistor** [comment]
I targeted the problem, `win.setBounds` effects. If `x` or `y` is not equals `0`, the click event will not have respond.

**Comment by lanistor** [comment]
I think it's the mouse event coordinate computed error when SendMessage, it didn't reduce the coordinate of Window.

**Comment by meslzy** [comment]
I didn't understand can u share a repo which has the issue and nodejs version u are using.

You can upload the code if it's easier.

**Comment by lanistor** [comment]
> I didn't understand can u share a repo which has the issue and nodejs version u are using.
> 
> You can upload the code if it's easier.

Such as the below image:
the BrowserWindow's coordinate is (200, 200), When you click (300, 300) of the PC screen, the coordinate that BrowserWindow received is also (300, 300), so the click pointer will actually to (500, 500) offset the PC screen.
It should receive (100, 100), the value of `(300, 300) - (200, 200)`;

![](https://raw.githubusercontent.com/lanistor/assets/master/flicker/electron-as-wallpaper.png)

**Comment by meslzy** [comment]
yes i mention this issue i said "native position" i knew this will happen its easy to fix ill make sure to fix that soon, is there any other issues like node version incompatibility or any thing!

**Comment by lanistor** [comment]
> yes i mention this issue i said "native position" i knew this will happen its easy to fix ill make sure to fix that soon, is there any other issues like node version incompatibility or any thing!

Another problem, when set `transparent=true` in `BrowserWindow`, after call attach, the window will disappear, it's weird.

Till now, i only tested in Windows11 by `node 16 ia32`, then i will test in more environments.

**Comment by meslzy** [comment]
okay, done.
ill close this issue. 

any new issue plz create new one for it.
