### ISSUE TITLE
When using your wallpaper to demonstrate the Win10 64 bit system, the icon did not display

### ISSUE THREAD

**Issue by kirbystudy** [meslzy/electron-as-wallpaper#6]
![2@KSH6$C1ONI E{A1 NI9HG](https://github.com/meslzy/electron-as-wallpaper/assets/63231787/57b05346-e118-4bc6-9aac-b3b2b5d523ea)

https://github.com/meslzy/electron-as-wallpaper/assets/63231787/f9d8d13c-c867-4fe1-89b6-fd50abb19e47

**Comment by meslzy** [comment]
Can you please describe the issue more?
What icon are you talking abt?

**Comment by kirbystudy** [comment]
My Question:

![TXI1LTF12 ZXPMP10WI07ZM](https://github.com/meslzy/electron-as-wallpaper/assets/63231787/4c8f73dc-30b1-42a4-aba9-a6dadfa33882)

![GC@T17RLRIX 40DDE24CVSF](https://github.com/meslzy/electron-as-wallpaper/assets/63231787/6b591554-165b-412a-849d-f66c2877c6b8)

1. According to the video demonstration, my system is running on Windows 10 64-bit, when I input the URL, I click on the "attach" button, wait for 5 seconds, and then click on the "show" button. The wallpaper will be applied, but the desktop icons will become invisible.

2. Second picture, At this particular location, an inexplicable additional window unexpectedly appears, causing confusion.

**Comment by meslzy** [comment]
are you saying you have issue with the app not the library? in that case i only built the app to demonstrate the funcalty its not ready for use by any user it doesn't has many features.

you may want to build ur own app using electron and nodejs.

**Comment by kirbystudy** [comment]
Yes, I am currently using your library and based on the demo example you provided, I have found that the issue is the same as the application.

**Comment by kirbystudy** [comment]
renderer.js
`
const { ipcRenderer } = require("electron")

const URL = 'https://dwbot.oss-cn-hongkong.aliyuncs.com/qd036.mp4'
const someArgument = { msg: 'Request to open wallpaper window', URL }

ipcRenderer.invoke('ask-open-wallpaper', someArgument).then((result) => {})
`

main.js
`
const { ipcMain, BrowserWindow, screen } = require("electron")
const { attach, detach, refresh } = require("electron-as-wallpaper")

ipcMain.handle('ask-open-wallpaper', async (event, someArgument) => {
    try {
        const { msg, URL } = someArgument

        global.shareVariable = {
            imgUrl: URL
        }

        if (!wallpaper) {
            wallpaper = new BrowserWindow({
                enableLargerThanScreen: true,
                autoHideMenuBar: true,
                fullscreen: true,
                frame: false,
                show: false,
                webPreferences: {
                    backgroundThrottling: false,
                    webSecurity: false,
                    nodeIntegration: true,
                    contextIsolation: false,
                    webviewTag: true
                }
            })
        }

        if (wallpaper) {
            require('@electron/remote/main').enable(wallpaper.webContents)
        }

        await wallpaper.loadURL(path.resolve(
            __dirname,
            '../../renderer/pages/wallpaper/wallWindow.html'
        ))

        attach(wallpaper)
        wallpaper.show()
        refresh()

        return 'ok'
    } catch (error) {
        console.error('Error asking to open wallpaper', error)
        return 'error'
    }
})
`

wallWindow.html
`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            width: 100vw;
            overflow: hidden;
        }
    </style>
</head>

<body>
    <video id="video" style="width: 100%; height: 100%; object-fit: cover;" autoplay loop muted></video>
    <script src="wallWindow.js"></script>
</body>

</html>
`

wallWindow.js
`
const { getGlobal } = require('@electron/remote')
const video = document.getElementById('video')
const { imgUrl } = getGlobal('shareVariable')

if (imgUrl) {
    video.src = imgUrl.replaceAll('\\', '/')
}
`

**Comment by meslzy** [comment]
Please read [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) first, its help you create better code so i can understand better.

in order to hide the icon in taskbar you may want to use `skipTaskbar` you can find more info [here](https://www.electronjs.org/docs/latest/api/browser-window)

**Comment by kirbystudy** [comment]
Sorry, the code for the main process was written according to your example code, which has the same issue as the application you published. My computer is on a Win 64 bit system, and the desktop icons have become invisible.

```js
   let wallpaper;
   app.on("ready", async () => {
   wallpaper = new BrowserWindow({
                enableLargerThanScreen: true,
                autoHideMenuBar: true,
                fullscreen: true,
                frame: false,
                show: false,
                webPreferences: {
                    backgroundThrottling: false,
                    webSecurity: false,
                    nodeIntegration: true,
                    contextIsolation: false,
                    webviewTag: true
                }
            })
  });

        await wallpaper.loadURL(path.resolve(
            __dirname,
            '../../renderer/pages/wallpaper/wallWindow.html'
        ))

  attach(wallpaper)
  wallpaper.show()
  refresh()
});
 ```

**Comment by meslzy** [comment]
```ts
  let wallpaper;
   app.on("ready", async () => {
   wallpaper = new BrowserWindow({
                enableLargerThanScreen: true,
                autoHideMenuBar: true,
                fullscreen: true,
                frame: false,
                show: false,
                skipTaskbar: true, // ADD THIS
                webPreferences: {
                    backgroundThrottling: false,
                    webSecurity: false,
                    nodeIntegration: true,
                    contextIsolation: false,
                    webviewTag: true
                }
            })
  });

        await wallpaper.loadURL(path.resolve(
            __dirname,
            '../../renderer/pages/wallpaper/wallWindow.html'
        ))

  attach(wallpaper)
  wallpaper.show()
  refresh()
});
```
