### ISSUE TITLE
I install and use that ，but I can't set the icon up to the wallpapeer，which one step does I not do

### ISSUE THREAD

**Issue by xiezhiyi163** [meslzy/electron-as-wallpaper#7]
import {attach, detach, refresh} from "electron-as-wallpaper";
// or
const {attach, detach, refresh} = require("electron-as-wallpaper"); // this is I use

attach(mainWindow); // and this is I use too,but not success,but nothing go wrong with the code
detach(mainWindow);

// if the window closed before detach, you can call refresh
refresh();

**Comment by meslzy** [comment]
When you run the application can you plz share a screen shot of the desktop wallpaper and also describe the issue more.

What icon that you can't set
