### ISSUE TITLE
Hello, can you provide the source code for the demo? I would be extremely grateful.

### ISSUE THREAD

**Issue by leoFitz1024** [meslzy/electron-as-wallpaper#8]
Hello, can you provide the source code for the demo? I would be extremely grateful.

**Comment by meslzy** [comment]
Absolutely, I'll add it nice commit

**Comment by leoFitz1024** [comment]
Thank you very much

**Comment by meslzy** [comment]
Couldn't not find the same demo i built before, but i recreate it again, take a look at [here](https://github.com/meslzy/electron-as-wallpaper/tree/main/exmaples/demo)
